export const ADMIN_PATENTS_REQUEST = 'ADMIN_PATENTS_REQUEST'
export const ADMIN_PATENTS_SUCCESS = 'ADMIN_PATENTS_SUCCESS'
export const ADMIN_PATENTS_FAIL = 'ADMIN_PATENTS_FAIL'

export const ALL_PATENTS_REQUEST = 'ALL_PATENTS_REQUEST'
export const ALL_PATENTS_SUCCESS = 'ALL_PATENTS_SUCCESS'
export const ALL_PATENTS_FAIL = 'ALL_PATENTS_FAIL'

export const PATENT_DETAILS_REQUEST='PATENT_DETAILS_REQUEST'
export const PATENT_DETAILS_SUCCESS='PATENT_DETAILS_SUCCESS'
export const PATENT_DETAILS_FAIL='PATENT_DETAILS_FAIL'

export const NEW_PATENT_REQUEST='NEW_PATENT_REQUEST'
export const NEW_PATENT_SUCCESS='NEW_PATENT_SUCCESS'
export const NEW_PATENT_RESET='NEW_PATENT_RESET'
export const NEW_PATENT_FAIL='NEW_PATENT_FAIL'

export const DELETE_PATENT_REQUEST='DELETE_PATENT_REQUEST'
export const DELETE_PATENT_SUCCESS='DELETE_PATENT_SUCCESS'
export const DELETE_PATENT_RESET='DELETE_PATENT_RESET'
export const DELETE_PATENT_FAIL='DELETE_PATENT_FAIL'

export const UPDATE_PATENT_REQUEST='UPDATE_PATENT_REQUEST'
export const UPDATE_PATENT_SUCCESS='UPDATE_PATENT_SUCCESS'
export const UPDATE_PATENT_RESET='UPDATE_PATENT_RESET'
export const UPDATE_PATENT_FAIL='UPDATE_PATENT_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'
